### ISSUE TITLE
Question: I want each to have an environment variable value

### ISSUE THREAD

**Issue by khs3131** [kubernetes-sigs/secrets-store-csi-driver#747] opened 2021-09-24 07:02 UTC
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I have one aws secret manager. There are five secret values in aws secret manager: username, password, engine, host, and port. I want to display the values of username, password, engine, host, and port respectively when connecting to the inside of the pod (exec -it) using the env field. For example, use the 'kubectl exec -it -- /bin/bash' command to access the pod and the result of the environment variable is USERNAME = admin / PASSWORD = ;g{}. /engine=mysql/host=rds01.mysql/port=3306 I want to show. But now it is displayed as a single line in json format as below. USERNAME=(PASSWORD={"username": "admin", "password": ";g{}.", "engine": "mysqldb", "host" : "rds01.mysql", "port": 3306} Is there any way to solve this?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Cloud Provier : AWS
- Secrets Store CSI Driver version: (use the image tag): k8s.gcr.io/csi-secrets-store/driver:v0.2.0
- Kubernetes version: (use `kubectl version`): EKS 1.21 / kubectl 1.21

**Comment by aramase** [comment] 2021-10-01 20:55
@khs3131 As this is specific to the AWS provider, could you open an issue [here](https://github.com/aws/secrets-store-csi-driver-provider-aws/issues) instead?

**Comment by aramase** [comment] 2022-01-31 21:58
duplicate of https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/49

/close

**Closed** 2022-01-31 21:58 UTC
Labels: kind/feature, lifecycle/rotten
