### ISSUE TITLE
Azure key vault volume not accessible, how to fix that?

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes-sigs/secrets-store-csi-driver#661] opened 2021-07-26 17:07 UTC
I have followed the walkthrough provided in this [link](https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/)

And at step 6, I have tried to create a pod with the volume linked to the keyvault.

But it is not able to access the volume.
```

kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
busybox-secrets-store-inline                 0/1     ContainerCreating   0          27s
csi-csi-secrets-store-provider-azure-2fwqd   1/1     Running             0          45m
csi-secrets-store-csi-driver-d6zjv           3/3     Running             0          45m


 kubectl describe pod busybox-secrets-store-inline
Name:         busybox-secrets-store-inline
Namespace:    default
Priority:     0
Node:         aks-agentpool-22716505-vmss000001/10.240.0.5
Start Time:   Mon, 26 Jul 2021 21:45:02 +0530
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:
IPs:          <none>
Containers:
  busybox:
    Container ID:
    Image:         k8s.gcr.io/e2e-test-images/busybox:1.29
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sleep
      10000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/secrets-store from secrets-store-inline (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g7shm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  secrets-store-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=azure-kvname
  default-token-g7shm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-g7shm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    3m50s  default-scheduler  Successfully assigned default/busybox-secrets-store-inline to aks-agentpool-22716505-vmss000001
  Warning  FailedMount  110s   kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  107s   kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-g7shm]: timed out waiting for the condition
```

**Comment by aramase** [comment] 2021-07-27 00:10
@ukreddy-erwin Thank you for reporting the issue. Here is the troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/. Could you provide the logs and other relevant info on the driver and provider version installed in the cluster?

1. Driver and provider version used
2. Logs from driver and provider pod running on the same node as your app
3. Kubernetes version
4. SecretProviderClass yaml
5. Pod yaml

For azure provider specific issues, you can open an issue at https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues.

**Comment by ukreddy-erwin** [comment] 2021-07-27 06:05
The SecretProviderClass and Pod yaml files are exact copies as in this [link ](https://azure.github.io/secrets-store-csi-driver-provider-azure/demos/standard-walkthrough/)

```

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\UReddy> kubectl get pods
NAME                                                              READY   STATUS              RESTARTS   AGE
aad-pod-identity-mic-5f6576748f-68qgq                             1/1     Running             0          9h
aad-pod-identity-mic-5f6576748f-dxqbg                             1/1     Running             0          9h
aad-pod-identity-nmi-4xz5l                                        0/1     CrashLoopBackOff    117        9h
csi-secrets-store-provider-azure-1627329606-secrets-store-dkm89   3/3     Running             0          9h
csi-secrets-store-provider-azure-1627329606-v8scd                 1/1     Running             0          9h
nginx-secrets-store-inline                                        0/1     ContainerCreating   0          9h
PS C:\Users\UReddy> kubectl get pods -l app=secrets-store-csi-driver -o wide
NAME                                                              READY   STATUS    RESTARTS   AGE   IP            NODE                                NOMINATED NODE   READINESS GATES
csi-secrets-store-provider-azure-1627329606-secrets-store-dkm89   3/3     Running   0          9h    10.244.0.10   aks-agentpool-22716505-vmss000001   <none>           <none>
PS C:\Users\UReddy> kubectl get pods -l app=csi-secrets-store-provider-azure -o wide
NAME                                                READY   STATUS    RESTARTS   AGE   IP           NODE                                NOMINATED NODE   READINESS GATES
csi-secrets-store-provider-azure-1627329606-v8scd   1/1     Running   0          10h   10.240.0.5   aks-agentpool-22716505-vmss000001   <none>           <none>
PS C:\Users\UReddy> kubectl logs csi-secrets-store-provider-azure-1627329606-secrets-store-dkm89 secrets-store --since=1h | grep ^E
E0727 05:02:09.721461       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:04:11.750962       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:06:13.770738       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:08:15.809638       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:10:17.833768       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:12:19.861134       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:14:21.896486       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:16:23.935262       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:18:26.048522       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:20:28.077339       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:22:30.087948       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:24:32.110801       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:26:34.137484       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:28:36.180694       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:30:38.201304       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:32:40.217686       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:34:42.243455       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:36:44.349315       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:38:46.366761       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:40:48.472380       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:42:50.603425       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:44:52.657831       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:46:54.680577       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.E0727 05:48:56.713736       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secreiled to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:50:58.748836       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:53:00.782730       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:55:02.807950       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:57:04.906916       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 05:59:06.963303       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
E0727 06:01:09.069617       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/nginx-secrets-store-inline, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: Get "http://localhost:2579/host/token/?resource=https://vault.azure.net": dial tcp 127.0.0.1:2579: connect: connection refused
PS C:\Users\UReddy> kubectl get version
error: the server doesn't have a resource type "version"
PS C:\Users\UReddy> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c18ff7bd5227b42c617cf371cf315d0423e91d5e", GitTreeState:"clean", BuildDate:"2021-05-25T17:38:04Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
PS C:\Users\UReddy>
```

**Comment by ukreddy-erwin** [comment] 2021-07-27 06:07
```
PS C:\Users\UReddy> helm list
NAME                                            NAMESPACE       REVISION        UPDATED                                STATUS   CHART                                   APP VERSION
csi-secrets-store-provider-azure-1627329606     default         1               2021-07-27 01:30:11.0024927 +0530 IST  deployed csi-secrets-store-provider-azure-0.0.20 0.0.16
pod-identity                                    default         1               2021-07-27 01:50:47.7645559 +0530 IST  deployed aad-pod-identity-4.1.2                  1.8.1
PS C:\Users\UReddy> helm status csi-secrets-store-provider-azure-1627329606
NAME: csi-secrets-store-provider-azure-1627329606
LAST DEPLOYED: Tue Jul 27 01:30:11 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
PS C:\Users\UReddy>
```

**Comment by aramase** [comment] 2021-07-27 16:51
duplicate of https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/590

/close

**Closed by aramase** 2021-07-27 16:51 UTC
Labels: kind/bug
